Github actions: Use Go 1.22 everywhere

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,7 +17,7 @@ jobs:
           mysql -e 'CREATE DATABASE ${{ env.MYSQL_TEST_E2E_DB }};' -u${{ env.MYSQL_TEST_USER }} -p${{ env.MYSQL_TEST_PASS }}
       - uses: actions/setup-go@v3
         with:
-          go-version: '^1.21'
+          go-version: '^1.22'
       - name: Set up Go
         run: |
           go get -u golang.org/x/lint/golint
@@ -108,7 +108,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-go@v3
         with:
-          go-version: '^1.21'
+          go-version: '^1.22'
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
@@ -147,7 +147,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-go@v3
         with:
-          go-version: '^1.21'
+          go-version: '^1.22'
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
@@ -186,14 +186,13 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/setup-go@v3
         with:
-          go-version: '1.21'
+          go-version: '^1.22'
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
       - name: Install dependencies
         run: |
           pip install wheel pytest
-          go get -v -t ./...
       - uses: ankane/setup-mysql@v1
         with:
           database: ${{ env.MYSQL_TEST_E2E_DB }}
@@ -208,19 +207,16 @@ jobs:
 
   test-windows:
     runs-on: windows-latest
-    env:
-      GOPATH: ${{ github.workspace }}
-      GO111MODULE: off
     defaults:
       run:
-        working-directory: ${{ env.GOPATH }}/src/github.com/google/fleetspeak
+        working-directory: ${{ github.workspace }}/src/github.com/google/fleetspeak
     steps:
       - uses: actions/setup-go@v3
         with:
-          go-version: '1.21'
+          go-version: '^1.22'
       - uses: actions/checkout@v3
         with:
-          path: ${{ env.GOPATH }}/src/github.com/google/fleetspeak
+          path: ${{ github.workspace }}/src/github.com/google/fleetspeak
       - uses: actions/setup-python@v4
         with:
           python-version: '3.10'
@@ -229,7 +225,7 @@ jobs:
         run: |
           # TODO: The dependency installation fails, but good enough to make the tests pass.
           # Ideally, required dependencies should be installed in a non-hacky, proper way.
-          go get -v -t ./... || echo "Dependency installation failed, continuing anyway ¯\_(ツ)_/¯"
+          # go get -v -t ./... || echo "Dependency installation failed, continuing anyway ¯\_(ツ)_/¯"
           pip install wheel
       - name: Build
         shell: bash
